# Generated by Django 3.2.3 on 2023-06-26 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ингридиент')),
                ('measurement_unit', models.CharField(max_length=30, verbose_name='единица измерения ингредиента')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='ингридиентов не может быть меньше 1'), django.core.validators.MaxValueValidator(30, message='ингридиентов не может быть больше 30')], verbose_name='количество ингридиентов')),
            ],
            options={
                'verbose_name': 'связь ингридиента с рецептом',
                'verbose_name_plural': 'связи ингридиентов и рецептов',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название шедевра')),
                ('image', models.ImageField(default=None, help_text='добавьте фото шедевра', upload_to='recipes/images/', verbose_name='как выглядит блюдо')),
                ('text', models.TextField(default='автор не добавил описание блюда', verbose_name='описание приготовления блюда')),
                ('cooking_time', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='приготовление не может занимать менее 1 минуты'), django.core.validators.MaxValueValidator(1440, message='приготовление не может занимать более одного дня')])),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата публикации рецепта')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipesCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='RecipeToTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'тег рецепта',
                'verbose_name_plural': 'теги рецептов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='тег')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='данное поле должно быть в формате HEX', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SelectedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeselect', to='recipes.recipe', verbose_name='избранные')),
            ],
            options={
                'verbose_name': 'избранный',
                'verbose_name_plural': 'избранные',
                'ordering': ('-id',),
            },
        ),
    ]
